# Generated by Django 3.0.7 on 2020-07-02 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ENnashmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtecher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuts', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std1', models.CharField(max_length=100)),
                ('t2', models.CharField(max_length=100)),
                ('date1', models.DateField()),
                ('reson', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuts', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('idsec', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('techer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.Addtecher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('Addtecher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.Addtecher')),
                ('stduentid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.student')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='rateandexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surah', models.CharField(max_length=100)),
                ('pagenumber', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('behavior', models.IntegerField()),
                ('points', models.IntegerField()),
                ('stduentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.student')),
                ('techerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.Addtecher')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('viewied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='atdence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('stuts', models.CharField(max_length=100)),
                ('sdtid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.student')),
                ('techerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.Addtecher')),
            ],
        ),
        migrations.CreateModel(
            name='addstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.student')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.Addtecher')),
            ],
        ),
        migrations.CreateModel(
            name='addadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuts', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
