# Generated by Django 3.0.7 on 2020-07-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ENnashmi', '0002_addadmin_addstudent_addtecher_atdence_message_notifications_rateandexam_student_studentform1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform1',
            name='Addtecher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.Addtecher'),
        ),
        migrations.AlterField(
            model_name='studentform1',
            name='stduentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ENnashmi.student'),
        ),
    ]
